name: Fix lint
on:
  push:
    branches:
      - dependabot/npm_and_yarn/eslint-*
      - dependabot/npm_and_yarn/prettier-*
jobs:
  fix-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Fix lint
        run: yarn lint:fix

      - name: Update PR
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: 'Lint fixed'
          body: 'An update to eslint or prettier required updates to your code.'
          branch: ${{ github.ref }}
          commit-message: 'style: fix linting issues'
