name: Publish
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NPM or Yarn install with caching
        uses: bahmutov/npm-install@v1.1.0

      - name: Lint
        uses: Borales/actions-yarn@1.1.0
        with:
          args: lint

      - name: Test
        uses: Borales/actions-yarn@1.1.0
        with:
          args: test

      - name: Build
        uses: Borales/actions-yarn@1.1.0
        with:
          args: build

      - name: 'Test: smoke'
        uses: Borales/actions-yarn@1.1.0
        with:
          args: 'test:smoke'
